### ISSUE TITLE
Odd failure when argument was undefined

### ISSUE THREAD

**Issue by h2oboi89** [ryanplusplus/mach.js#23]
``` sh
1) HostedGeaNode should expose geaNode.bind
1.1) TypeError: Cannot read property 'constructor' of undefined
    TypeError: Cannot read property 'constructor' of undefined
        at argString (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\node_modules\mach.js\index.js:18:16)
        at UnexpectedArgumentsError (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\node_modules\mach.js\index.js:64:52)
        at Function.mockHandler (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\node_modules\mach.js\index.js:226:15)
        at GeaNode.mock [as _bind] (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\node_modules\mach.js\index.js:310:24)
        at HostedGeaNode.bind (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\src\HostedGeaNode.js:46:19)
        at geaNode.bind.shouldBeCalled.when (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\spec\HostedGeaNode_spec.js:88:18)
        at Object.when (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\node_modules\mach.js\index.js:235:7)
        at Object.it (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\spec\HostedGeaNode_spec.js:87:35)
        at attemptSync (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1886:24)
        at QueueRunner.run (C:\Users\220040509\workspace\ApplianceTools\ApplCore\GeaNodePlugin\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1874:9)
```

**Comment by ryanplusplus** [comment]
Looks like https://github.com/ryanplusplus/mach.js/issues/13 and the stack trace looks like an old version. Are you sure you're using the latest goodness?

**Comment by h2oboi89** [comment]
Could be. Was mostly focused on capturing the trace real quick and moving on. I think we can ignore this.
